### ISSUE TITLE
some syntax error on installing

### ISSUE THREAD

**Issue by lanybass** [daavoo/pyntcloud#1]
byte-compiling build\bdist.win32\egg\pyntcloud\pyntcloud.py to pyntcloud.pyc
  File "build\bdist.win32\egg\pyntcloud\pyntcloud.py", line 357
    def get_KDTree(self, *args, element='vertex', and_set=True):
                                      ^
SyntaxError: invalid syntax

byte-compiling build\bdist.win32\egg\pyntcloud\ransac\ransac.py to ransac.pyc
byte-compiling build\bdist.win32\egg\pyntcloud\ransac\ransac_models.py to ransac_models.pyc
  File "build\bdist.win32\egg\pyntcloud\ransac\ransac_models.py", line 87
    return proj_points, norm_all(orthogonal_projection)
SyntaxError: 'return' outside function

**Comment by daavoo** [comment]
Hi!

The first syntax error I suspect that is because you are not using python3 (my fault, I now specified that this is the required version in the README). You can read [more info here](https://www.python.org/dev/peps/pep-3102/). Anyway I change the sintax of the function.

The second one is fixed.

Please be aware that I haven't released the 0.1 version yet and there is a lot of changes that I haven't comitted.

Thanks
