### ISSUE TITLE
Refresh plot

### ISSUE THREAD

**Issue by fferroni** [daavoo/pyntcloud#144]
Hi,

Is it possible to refresh the point cloud plot? i.e. displaying a video of point clouds whilst still being able to interact in the browser and changing views?
Alternatively is it possible to take PNGs rather than HTMLs ?

Thanks!

**Comment by daavoo** [comment]
- Sorry but displaying a "stream" of point clouds is not currently possible and I don't think it will be added any time soon unless it comes from a external contribution. There might be some options for what you want out there. Maybe [this link](http://wiki.ros.org/ros3djs/Tutorials/Point%20Cloud%20Streaming%20from%20a%20Kinect) can help you.

- There is a "Take screenshot" button that should generate a PNG file from the current view of the HTML

**Comment by daavoo** [comment]
Closing this. Feel free to reopen if your doubts have not been resolved :)

**Comment by Nicholas-Mitchell** [comment]
@daavoo - could you explain the limitations of the current implementation with regards to refreshing the pointcloud?

Is the pointcloud loaded into memory for the `pythreejs` session manager, just once at the beginning, then we are modifying the representation of static data? I assume this is what would make streaming pointclouds unbearably slow? 

My current use-case is that I have binary files on disk and would simply like to play through them to create a video. Manipulating the pointclouds at the same time would be nice to (just with the mouse I mean, not programmatically with callback functions etc.)

I know of ROS and rViz, which you linked above, but would love to get this running in Jupyter notebooks.

**Comment by Nicholas-Mitchell** [comment]
@daavoo 

**bump**  - is there anything you can say regarding my questions above?  :smile:

**Comment by daavoo** [comment]
Hi @Nicholas-Mitchell . I totally forgot about this :angel: 

I would need to take a look to pythreejs internals to see how viable(if possible) the streaming is.

I have some code for streaming point clouds with PyQt somewhere. I'll try to find it and come back with some updates.

**Comment by walzimmer** [comment]
I am also interested in displaying a sequence of point clouds (to animate it).
I know there is a "Take screenshot" button, but taking manually screenshots of more than 1000 frames is very time consuming. Can this be automated e.g. cloud.save(screenshot.png) instead of clicking the button?

**Comment by Nicholas-Mitchell** [comment]
@walzimmer

What I am requesting here, is to actually stream pointclouds in order to
make a video through time. I am not particularly interested in screenshots,
as that really would be a simple workaround to fix at the end. The bigger
problem here is really the ability to load and display individual
pointclouds files (whichever format they may be in) - to stream them. Tools
such as RViz (in the world of ROS) are able to do this, but the pointcloud
files are already contained within a single files (called a rosbag).

As an a side: if you want a video of you manipulating a loaded pointcloud,
you can simply use an app that can record a portion of the screen. On
Linux, I have been using Kazam. Here is an example video:
https://www.dropbox.com/s/i28hfckkpn4juab/interactive_point_cloud.mp4?dl=0
I mention this just as an alternative to using screenshot buttons. Perhaps
it'll lead you to other ideas.

**Comment by daavoo** [comment]
Should be doable now with Pyvista #248 

See comment:

https://github.com/daavoo/pyntcloud/issues/225#issuecomment-502875349
