### ISSUE TITLE
Rendering Method

### ISSUE THREAD

**Issue by MadhavEsDios** [daavoo/pyntcloud#167]
Hey first of all, really amazing work with this library !

Do you plan on changing the rendering framework from javascript(three.js) to lets say something pythonic like python-vtk, mayavi, etc 
But I assume there will be some pros and cons too,
1) I feel that three.js is very well maintained and has most of the 3D functionalities that anyone might need, plus the rendering was surprisingly good and fast. Plus it is a very popular topic on Stack Overflow. One drawback is that it uses javascript, because of which python programmers might find it uncomfortable to make changes.
2) Frankly speaking, I do not know of many purely pythonic 3D rendering frameworks and am not entirely sure even if they do exist, if they have great Stack Overflow following / documentation.

Was there any particular reason you chose three.js, what are your thoughts about this ?

**Comment by daavoo** [comment]
Hola! Thank you very much.

You are opening my personal pandora's box with this, xD.

The pros and cons you are listening are exactly the ones that I had in my mind when I chose to code the current UGLY AND DIRTY threejs rendering. And I think that those pros/cons are still valid. Each hour I dedicate to the .js rendering code I feel like I could have done 10x times more useful things in the Python API.

Rather than changing the current rendering, what I'm planning to do is extend the avaliable options for `PyntCloud.plot()`  probably via and optional arg `backend="something_better_than_threejs"` or something like that.

Back in the old days, I chose threejs because it was the "only" viable option to plot a point cloud inside a Jupyter Notebook, wich was the main usage platform I was targeting.

I spent some time back then to search for a viable "pure" python 3D rendering library for notebooks and discard many of the one you list  (python-vtk, mayavi) for diverse reasons: notebooks not (easily?) supported, python3 not supported, etc.

I'm not really up-to-date with the current state of 3D rendering in Python and all opinions/contributions are welcome.

I'm "working" (turtle mode) on [pyside2 ](http://wiki.qt.io/Qt_for_Python) and [pythreejs](https://github.com/jupyter-widgets/pythreejs) (my favourite choice so far) "backends" with promising results.

I really think that the key might be to have multiple backends because there are many use cases beyond Jupyter Notebooks.

**Comment by MadhavEsDios** [comment]
Hahahaha, I felt the same way about .js,when I was trying to make changes to the html file, but your hack was still surprisingly fast ;)
Also you are very right, jupyter notebook although very easy to use, might not be the preferred use case of many programmers. 
I myself have made changes to the plot function, replacing the IPython code with that of PyQt5, performance is still very good,(you have a bigger window) but the pain of generating html, ply, json files still exists.
My use case was to make the plot interactive, for example draw bounding boxes on objects inside a scene loaded from a .las file, for now the only good option I can come up with is three.js :(
I will keep you informed, if I come across better pythonic rendering frameworks, thanks !!!

**Comment by daavoo** [comment]
Pyvista has been added in #248 and before there was support for pythreejs and matplotlib as alternatives to three.js

Further backends should be easily integrated following the current examples
