### ISSUE TITLE
Installation guidelances 

### ISSUE THREAD

**Issue by andreaschaimalas** [daavoo/pyntcloud#171]
Hi everyone,
I am a newbie here and in programming in general. Started python a couple of hours ago, so please show some sympathy. 

I have downloaded the library and managed to install the project interpreter. 

I am using Pycharm as my IDE btw. I open a new project and add the pyntcloud file. When i try to run the setup.py I am getting the following error:

"usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help

error: no commands supplied "

Do you know how I can resolve this? Is this the correct way to install and run the pyntcloud ? (I have never downloaded anything from github).

Thank you for your patience and time.

**Comment by daavoo** [comment]
Hola!
Thanks for posting :)

So I'm not fully understanding how you are trying to install pyntcloud but I'll try to help.

There are many things that might be happening.

First of all, I recommend you to try to follow the instructions in http://pyntcloud.readthedocs.io/en/latest/installation.html and see if you manage to get that done.

The error you are getting there is because you are not passing any arguments to `setup.py`. You should run, from the root of the downloaded repository (pyntcloud in this case):

```bash
python setup.py install
````
*Or* if you want to edit the source files:

```bash
python setup.py develop
````
Wich will update the package each time you modify it without requiring you to re-install it.

Hope that some of this helps. Please don't hesitate to comment if you encounter problems

**Comment by daavoo** [comment]
@andreaschaimalas Closing this. Feel free to re-open if you have any more doubts

**Comment by nuria666** [comment]
Hello,

I have installed pyntcloud following the instructions in https://pyntcloud.readthedocs.io/en/latest/installation.html and the library seems to be installed in the new environment. However, when I try to view my data I get the following error:


  File "<ipython-input-3-0c84d324f306>", line 1, in <module>
    from pyntcloud import PyntCloud

ImportError: cannot import name 'PyntCloud'

I have tried to set up the anaconda environment and set up pyntcloud several times but I always get the same error. Those are the commands I have used in case it helps finding out the problem:

>conda create -n pyntcloud python=3.6 numpy numba scipy pandas
>conda activate pyntcloud
>conda install git pip
>python -m pip install git+git://github.com/daavoo/pyntcloud.git
>cd pyntcloud
>python setup.py install

I am using Anaconda2 in Windows 7.

Does someone know how can I get pyntcloud to work? From the library documentation it seems to be the right tool to look at my point cloud data.

Thank you in advance,

Nuria

**Comment by daavoo** [comment]
Hola @nuria666 !!
You have encountered a "bug" introduced yesterday :) (it is just a missing import, your pyntcloud instllation is fine but the code examples in the docs won't work) 

It should be fixed now, just re-clone the repository

**Comment by nuria666** [comment]
Hola!

Thank you for your quick response!
I have installed pyntcloud now and it seems to read my point cloud file and do other things with it. However, every time I try to visualise the point cloud or any other structure I get error messages related to pythreejs. I have installed pythreejs and ipywidgets libraries in my Anaconda environment. I have also installed matplotlib. Still I keep having errors when I try to plot. This is the latest one (after installing those libraries):


  File "C:\ProgramData\Anaconda2\envs\pyntcloud\lib\site-packages\pyntcloud\core_class.py", line 707, in plot
    return plot_with_pythreejs(self, **args)

  File "C:\ProgramData\Anaconda2\envs\pyntcloud\lib\site-packages\pyntcloud\plot\pythreejs_backend.py", line 83, in plot_with_pythreejs
    points = get_pointcloud_pythreejs(cloud.xyz, colors)

  File "C:\ProgramData\Anaconda2\envs\pyntcloud\lib\site-packages\pyntcloud\plot\pythreejs_backend.py", line 18, in get_pointcloud_pythreejs
    points_geometry = pythreejs.BufferGeometry(

AttributeError: module 'pythreejs' has no attribute 'BufferGeometry'

Do you know how can I resolve this problem?

A bit more of information, in case it helps: I'm trying to do some of the stuff you do in your example notebooks but using my own data. However, I am writing the scripts in Spyder instead of running them in Jupyter. Could that be the problem?

Thank you very much for your help. Kind regards,

Nuria
