### ISSUE TITLE
Seeing plots in Jupyter using QuickStart file

### ISSUE THREAD

**Issue by nandoLidar** [daavoo/pyntcloud#172]
Hola!
Great job with this library! I'm just getting started using it and it's definitely going to be really useful for my work.

I went through most of the issues and I see that there's been similar issues to what I'm getting with the .plot() function. I've tried those solutions but just haven't been able to figure it out yet.

I'm running your QuickStart file, and when I get to the first scene.plot() all I see is a black screen with the word 'screenshot' in an orange box in the top left and the logo in the middle of the screen. I'm using a Mac and Chrome. I have no clue where I should be looking and any help would be appreciated! Thanks!

**Comment by daavoo** [comment]
Hola :)
Thank you very much!

The plot function is now my official archenemy, it seems to cause many problems.


Have you tried any of the solutions commented in #138 ???

Could you try if the plot works in firefox?

**Comment by nandoLidar** [comment]
I just tried those again and starting an http server is working!

Firefox wasn't working, and neither was Safari.

The only issue now is that all points seem to default to orange unless they come from a .ply file... 
even if I replicate the data in a separate .csv file (for example copying all the points from diamond.ply into my own .csv file) the points will default to orange.

Has this been an issue before? the "use_as_color" or even the "cmap" options don't seem to do anything in these cases either.

Thank you for your help!

**Comment by nandoLidar** [comment]
Here's a simple snippet based on my trials. I still cannot get the plot function to work without starting a simple server
[manual_csv_test.csv.zip](https://github.com/daavoo/pyntcloud/files/2054819/manual_csv_test.csv.zip)

[example_fixing_orange.py.zip](https://github.com/daavoo/pyntcloud/files/2054821/example_fixing_orange.py.zip)

**Comment by daavoo** [comment]
Ok so there are 2 different issues here.

---

First, when using **Chrome**, the reason because you need to start a simpel server is because by default Chrome does not allow to load local files vía javascript. You can verify that this is the issue by openning the Chrome console on the page where you are loading the html, and you should see the error:
````
Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https.
````

However, when using **Firefox** you should be able to open the generated html and visualize the output without starting a server. Safari no idea.

---

The other issue is related with the .csv file header. If you look carefully, there are 2 unnecesary spaces on the right of `red `and `blue` which are making PyntCloud to don't interpret those columns as colors.

If you remove those spaces like in this file:

[fixed_csv_test.zip](https://github.com/daavoo/pyntcloud/files/2064924/fixed_csv_test.zip)

Your script should now run properly

**Comment by nandoLidar** [comment]
This is the error I'm getting in the Chrome console.

Failed to load http://localhost:8888/files/dev/point_cloud/notebooks/lidar_room_plot.config.json: Redirect from 'http://localhost:8888/files/dev/point_cloud/notebooks/lidar_room_plot.config.json' to 'http://localhost:8888/login?next=%2Ffiles%2Fdev%2Fpoint_cloud%2Fnotebooks%2Flidar_room_plot.config.json' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'null' is therefore not allowed access.

Is this still the same error that you're mentioning?

And great catch on the headers! Thank you!

**Comment by daavoo** [comment]
> Is this still the same error that you're mentioning?

Yes, that error means that Chrome is not allowing yo to load a local file, that's why you need to launch a simple http server or run the crhome executable with the following flag:

 `google-chrome --disable-web-security`

**Comment by ScarlettLeong** [comment]
It seems that the html file work on Firefox
