### ISSUE TITLE
Python 2 Support?

### ISSUE THREAD

**Issue by JeremySMorgan** [daavoo/pyntcloud#193]
Is there anyway to run this with python2?

**Comment by daavoo** [comment]
Hola @JeremySMorgan ! Thanks for your interest.

It is not possible to run pyntcloud with python2 out of the box. The lack of support for Python2 is intended, although I would be happy to help with indications to anyone who *really* needs to run this on Python2.

I think that trying to add python2 support to the full API would be an unjustifiable effort instead of using python3, but, if you really need to use python2 you could try to isolate the parts of the code that you really want to use and use a tool like https://wiki.python.org/moin/3to2 as first step. I can't guarantee that this will work out of the box but it will probably leave you with less work to do.

If you follow along with trying to run pyntcloud on python2, don't hesitate to open new issues as you encounter new problems.
