### ISSUE TITLE
Unable to plot color in PCD file

### ISSUE THREAD

**Issue by ravijo** [daavoo/pyntcloud#203]
I am trying to visualize a ASCII PCD file. Below is a some part of the content of this file-

```
# .PCD v0.7 - Point Cloud Data file format
VERSION 0.7
FIELDS x y z rgb
SIZE 4 4 4 4
TYPE F F F F
COUNT 1 1 1 1
WIDTH 38736
HEIGHT 1
VIEWPOINT 0 0 0 1 0 0 0
POINTS 38736
DATA ascii
1.4766392 -0.82155049 -0.0032610297 1.7976693e-38
1.4766392 -0.81364399 -0.0032610297 1.7884862e-38
1.4766392 -0.80577451 -0.0032610297 1.78845e-38
1.476639 -0.79794157 -0.0032609701 1.7607545e-38
1.476639 -0.79014462 -0.0032609701 1.7883416e-38
1.476639 -0.78238314 -0.0032609701 1.7791942e-38
1.476639 -0.77465671 -0.0032609701 1.769975e-38
1.476639 -0.76696479 -0.0032609701 1.6409733e-38
1.476639 -0.75930673 -0.0032609701 1.6593762e-38
```
Below is the code snippet-

```
from pyntcloud import PyntCloud

cloud = PyntCloud.from_file("file.pcd")
cloud.plot(background='white', initial_point_size=0.01)
```
Issues
---------
The generated plot has following issues-
* The background color is black (I was expecting it to be white)
* All the points are orange colored (the original cloud isn't orange colored)

Questions
-------------
1. How to set background color?
1. How to view original color of the cloud?
1. Is it possible to use this library without jupyter in standalone python code?

Additional info
------------------
1. `cloud.points.head()` prints following values-
```
x	y	z	rgb
0	1.476639	-0.821550	-0.003261	1.797669e-38
1	1.476639	-0.813644	-0.003261	1.788486e-38
2	1.476639	-0.805775	-0.003261	1.788450e-38
3	1.476639	-0.797942	-0.003261	1.760755e-38
4	1.476639	-0.790145	-0.003261	1.788342e-38
```
2. `cloud` prints following values-
```
PyntCloud
38736 points with 1 scalar fields
0 faces in mesh
0 kdtrees
0 voxelgrids
Centroid: 2.4970028400421143, 1.602269367140252e-05, 0.19447940587997437
Other attributes:
```

**Comment by daavoo** [comment]
Hola! Thanks for the very detailed issue report :)

Please have in mind that the pcd io functions are still a work in progress #132 (It has been a long time since I worked on it because I wasn't receiving user demmands).

Regardig your questions:

1 - If you are using the `pythreejs` backend for `PyntCloud.plot` (This is the default backend in the current master branch, you might want to pull the latest changes) you should see a color picker bellow the plot which let's you select the background color.

2 - The problem here is that the read_pcd fuction is not decoding the compacted rgb values. This should be easy to fix and I'd try to do it myself soon. You can "hack" a solution as follows:

```python
rgb = cloud.points["rgb"].values
cloud.points["red"] = np.asarray((rgb >> 16) & 255, dtype=np.uint8)
cloud.points["green"] = np.asarray((rgb >> 8) & 255, dtype=np.uint8)
cloud.points["blue"] = np.asarray(rgb & 255, dtype=np.uint8)
```
This conversion could be integrated inside read_pcd. Contributions are wellcome :)

3 - Yes, it is possible to use the library on any python script. Jupyter is not a mandatory dependency. However the `plot` functionality is only supported in Jupyter, for now. I'm working on a matplotlib backend which would be usable without jupyter. Keep an eye on #179

Hope that this answer your questions. Closing this, feel free to re-open if you consider that your issue still persists.

**Comment by ravijo** [comment]
@daavoo : Hola!

1. It seems that this problem is from `pythreejs` backend side.

2. Unpacking the RGB values worked. thanks for the quick hack. However there was one more step required before unpacking. By default PCL (till now, i.e. PCL v 1.8) stores RGB information in a float variable. You may have a look at official documentation [here](http://docs.pointclouds.org/trunk/structpcl_1_1_point_x_y_z_r_g_b.html). Hence, we need to treat these RGB values as int before we apply shifting operation. 

> This conversion could be integrated inside read_pcd. Contributions are wellcome :)

Thank you very much. I forked the repo and did the changes. Please see [here](https://github.com/ravijo/pyntcloud/commit/7b4205e64d5ed09abe708b2e91b615690c24d518). A [pull request](https://github.com/daavoo/pyntcloud/pull/204) has been created as well.

3. Would love to use the `plot` functionality in a standalone python code.

Thanks

**Comment by daavoo** [comment]
#204
