### ISSUE TITLE
How to plot two data frames together with different point size

### ISSUE THREAD

**Issue by ravijo** [daavoo/pyntcloud#205]
I have two data frames, each of them contains following columns `x, y, z, red, green, blue`. 
```
col = ['x', 'y', 'z', 'red','green','blue'] #columns for dataframe
N1 = 100 # number of points
p1 = np.random.random((N1, 3))
c1 = np.random.randint(0, 256, size=(N1, 3), dtype=np.uint8)
df1 = pd.DataFrame(data=np.hstack((p1, c1)), columns=col)

N2 = 10 # number of points
p2 = np.random.random((N2, 3))
c2 = np.zeros((N2, 3), dtype=np.uint8)
c2[:, 0] = 255 # red color
df2 = pd.DataFrame(data=np.hstack((p2, c2)), columns=col)

c1 = PyntCloud(df1)
c2 = PyntCloud(df2)
```
The above two clouds can easily be plotted independently using the following code-
```
c1.plot(initial_point_size=0.02)
c2.plot(initial_point_size=0.1)
```
However, **I want to visualize these two data frames together**. In my real environment, the first data frame is a point cloud of a scene and second data frames are the annotated points in 3D space. Since recognizing a point in a point cloud is difficult, so I thought of increasing the point size for annotations making them bigger and easy to recognize.

Any suggestions, please?

**Comment by daavoo** [comment]
Hola @ravijo ! 

I'm currently working on a refactor of the plot function in order to make it more flexible.  Adding support for rendering multiple things has been already requested #159 #124 and it'd be one of the new features.

I think that it's not worth to hack around trying to accomplish this with the current master branch given that I expect to merge the refactor no later than this weekend. Please stay tunned because I've almost finished.

**Comment by daavoo** [comment]
This works for me after #206 merge:

```python
col = ['x', 'y', 'z', 'red','green','blue'] #columns for dataframe
N1 = 100 # number of points
p1 = np.random.random((N1, 3))
c1 = np.random.randint(0, 256, size=(N1, 3), dtype=np.uint8)
df1 = pd.DataFrame(data=np.hstack((p1, c1)), columns=col)

N2 = 10 # number of points
p2 = np.random.random((N2, 3))
c2 = np.zeros((N2, 3), dtype=np.uint8)
c2[:, 0] = 255 # red color
df2 = pd.DataFrame(data=np.hstack((p2, c2)), columns=col)

c1 = PyntCloud(df1)
c2 = PyntCloud(df2)
```
On one cell:
```python
scene = c1.plot(initial_point_size=0.02, return_scene=True)
```
The scene is showed in the output of the cell.

Then on other cell:
```python
c2.plot(initial_point_size=0.1, scene=scene)
```
This only shows the poin size slider but the points are showed in the output of the above cell.

Hope that this is what you wanted !

PD. You might want to consider plotting the "annotated"points as pythreejs spheres for better visualization. I might add an example of this soon. The key is to update the `scene.children` like in:

https://github.com/daavoo/pyntcloud/blob/master/pyntcloud/core_class.py#L746

But instead of `points` you could add any pythreejs figure:
https://github.com/jupyter-widgets/pythreejs/blob/master/examples/Geometries.ipynb
