### ISSUE TITLE
`plot` doesn't plot in IPython console in Spyder IDE

### ISSUE THREAD

**Issue by IvanKush** [daavoo/pyntcloud#219]
`plot` doesn't plot in **IPython console** in **Spyder** IDE

Code:
```
cloud = PyntCloud(df)
...
cloud.plot()
```

Get message, but nothing plots  =((
```
loading images...
~/projects/ml/lib/python3.5/site-packages/pythreejs/traits.py:175: UserWarning: 64-bit data types not supported for WebGL data, casting to 32-bit.
  warnings.warn('64-bit data types not supported for WebGL '
Renderer(camera=PerspectiveCamera(aspect=1.6, fov=90.0, position=(359.5, 1918.5, 610.707568359375), quaternion…
HBox(children=(Label(value='Point size:'), FloatSlider(value=127.9, max=1279.0, step=1.2790000000000001), Labe…
```

**Comment by skariel** [comment]
I have the same issue but on a Jupyter notebook... (ubuntu 18)

**Comment by daavoo** [comment]
Hola @IvanKush ! Thanks for reporting. Unfortunately, the issue here is directly not related to`pyntcloyd`. The issue is that Spyder's ipython console does not support displaying html (See answer from spyder mantainer: https://stackoverflow.com/questions/47075946/replicate-jupyter-html-output-using-ipython-and-spyder-instead/47084058#47084058). 

You should be able to see the result of the plot in a Jupyter notebook.

You could move the issue to `spyder` https://github.com/spyder-ide as a feature request

**Comment by daavoo** [comment]
Hola @skariel It looks like your issue is not exactly the same because @IvanKush issue is related to spyder, not jupyter notebooks. Could you please open a different issue given a little more details about your problem?

**Comment by rsj007** [comment]
> r notebooks. Could you please open a different issue given a little more details about your problem?

I also meet this issue. Have you solved it?
