### ISSUE TITLE
Licensing terms?

### ISSUE THREAD

**Issue by egeerardyn** [daavoo/pyntcloud#224]
What are the licensing terms of pyntcloud? 

Some of my colleagues and me are currently looking into using Pyntcloud for our daily work, but without a license (and yes, I know those contain legalese, I don't like it either), it becomes quite impossible for us to use Pyntcloud in a business setting since we don't know what we can and cannot do with the code (e.g. can we use the code, can we store it on our internal server, can we distribute to our customers, can we make changes, ...)

So would you be so kind to look into attaching a boring old license to Pyntcloud? MIT or BSD is pretty liberal and straightforward, I'd say. But of course, feel free to choose whatever you deem fit.

Please also see https://blog.stanko.io/licensing-software-b13d043e2a93 for a bit more information about OSS licenses.

**Comment by daavoo** [comment]
Hola @egeerardyn!  Sorry for the late reply and the inconvenience.

To cut a long story short, you can create a *fork of the project using the Github button* (a concept surprisingly absent in most of those licenses) and do whatever you want. I would need to hire some pretty damm expensive layers to spend 50 hours researching about precedents of forked unlicensed projects at Github. 

Even if in that scenario you have some legal concerns, I would happily write and sing for you a legal document allowing you to do whatever you want with pyntcloud (except if you are working on some Jurassic park shit in which case I demmand you to include me in the project).

Long story:

I have already looked about the available open source licenses many times (I even received serveral hours of "boring" training at work about the subject) and I took the decision of not including one because of personal opinions about the system, not because I didn't care about the subject or because I found licenses boring. 

This is a debate that I have already had many times with colleagues and I don't really see how I could change my mind.

Given the current nature of the project where 99% of the code is still added by myself and given that, you are the first and only person so far that have reached me with the need of a license, I'm not planning to add one in the short term.

If the day comes when some people apart from me are actively adding code to the project and they want to add a license or a lot of users demmand it, I might consider the addition of some kind of license.
