### ISSUE TITLE
Help installing pyntcloud

### ISSUE THREAD

**Issue by Aventhera** [daavoo/pyntcloud#227]
Hello,
We are students working on 3D reconstruction and we would like to use pyntcloud in order to create a point cloud from 2D images. 
Unfortunately, we can't install pyntcloud using the line "pip install git+https://github.com/daavoo/pyntcloud". 
We are currently working on python 3.x.x, using pyzo as the editor and get "Collecting git+https://github.Error in pip command:
'utf-8' codec can't decode byte 0xe9 in position 142: invalid continuation byte" as an error. As we are quite new to python, openCV etc we don't know how to solve that problem. Would you mind helping us?

**Comment by jsuyanyong** [comment]
Have you try to install pyntcloud in new anaconda virtual environment?

**Comment by Aventhera** [comment]
I don't really understand what you mean by anaconda virtual environment. We're using pyzo and when we start a shell we got a message saying "Python 3.6.2|Anaconda, Inc.|", isn't it already the anaconda environment? If not, do you have any link where we could get this virtual environment please?

**Comment by daavoo** [comment]
Hola @Aventhera thanks for the report and sorry for the inconvenience. Also thanks @jsuyanyong for trying to help.

Unfortunately, I'm not familiar with `pyzo` so I'm not sure if your problem is related with `pyntcloud` or with `pyzo`. I think that you could try to pass the issue to `pyzo` https://github.com/pyzo/pyzo to see if they can give you more info about the problem. If after their feedback you found that the problem is related with pyntcloud, please don't  hesitate to open a new issue.
