### ISSUE TITLE
load obj with color files got error

### ISSUE THREAD

**Issue by beyondzzz** [daavoo/pyntcloud#245]
**Describe the bug**

**To Reproduce**
1. find a obj with color file
2. python 3.6
3. code:

from pyntcloud import PyntCloud
PyntCloud.from_file(pathfile)

Traceback (most recent call last):
  File "pre.py", line 14, in <module>
    PyntCloud.from_file("/Users/mac/Documents/wayback/test_files/" + eachFile)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pyntcloud/core_class.py", line 128, in from_file
    return cls(**FROM[ext](filename, **kwargs))
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pyntcloud/io/obj.py", line 61, in read_obj
    for i in range(f[0].count("/") / 2):
TypeError: 'float' object cannot be interpreted as an integer

**Expected behavior**
my solution (maybe not the best way):

 for i in range(f[0].count("/") / 2):

 for i in range(f[0].count("/") // 2):

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [mac]

**Additional context**

**Comment by daavoo** [comment]
Hola @beyondzzz , could you share an example file that raises this error?

**Comment by khaiyichin** [comment]
Hi @daavoo, I have the exact error, but on a Ubuntu 20.04 system. Since this hasn't been addressed I thought I could provide an example file [cafe.zip](https://github.com/daavoo/pyntcloud/files/5968762/cafe.zip) that you can use to replicate the error.

I simply loaded the `cafe.obj` file and the error described by @beyondzzz appears (the one related to `read_obj`)
```
map_mesh = PyntCloud.from_file(map_filepath) # map_filepath is cafe.obj
```

The `pyntcloud` package was installed via PyPI.
