### ISSUE TITLE
OA/OS licence 

### ISSUE THREAD

**Issue by bsburnham** [daavoo/pyntcloud#246]
This is a simple request or question I have about making this library open access and open source?

I realise that it has an Unlicence, but if other developers want to include some of the type of data that can created and 'exported' from here, then they _should_ have the same licence attributed to it. 

Thoughts?

**Comment by banesullivan** [comment]
I too am a bit confused by this... I've never heard of an "Unlicense"

Would you all consider relicensing this project to an [Open Software Initiative](https://opensource.org/licenses/) or [Free Software Foundation](https://www.fsf.org/licensing/licenses/) approved license that fits the motivations of this project?

Personally I'd love to see an MIT License with this project, but this is very much a decision for the original authors and I'll support whatever they chose to do.

@daavoo, could this issue be addressed/closed before moving forward with #248 so that we (from PyVista) can properly link to this library for our users that want to have fun with Pynt clouds?

**Comment by daavoo** [comment]
MIT is now the official LICENSE
