### ISSUE TITLE
Extract Eigenvalues and Anisotropy

### ISSUE THREAD

**Issue by denabazazian** [daavoo/pyntcloud#269]
I have two issues to comment regarding the Eigenvalues, one about extracting the three eigenvalues associated to each point and the other about computing Anisotropy. 

1) To extract the three eigenvalues associated to each point, I am trying something as the following code: 
`from pyntcloud import PyntCloud`
`pcd1 = PyntCloud.from_file("bunny.pcd")`                                                                       
`kdtree_id = pcd1.add_structure("kdtree") `                                               
`k_neighbors = pcd1.get_neighbors(k=65, kdtree=kdtree_id)   `                               
`ev = pcd1.add_scalar_field("eigen_values", k_neighbors=k_neighbors)`
and as ```ev```, I get: `['e1(66)', 'e2(66)', 'e3(66)']` .  
For whatever `K` that I try to calculate the eigenvalues, I receive something as `['e1(K+1)', 'e2(K+1)', 'e3(K+1)']` and each `e(k+1)` is a string. 
Is there any other straight forward way to get the three eigenvalues associated to each point? 

2) To computing anisotropy, based on the example in this [link](https://github.com/daavoo/pyntcloud/blob/master/examples/%5Bscalar_fields%5D%20eigenvalues.ipynb): 
`A_lambda = (lambda_1 - lambda_2)/lambda_3` . 
However, in this [link](https://github.com/daavoo/pyntcloud/blob/master/pyntcloud/scalar_fields/eigenvalues.py#L30), it is written in a different way. I think either the equation or the code is not correct. If the equation is right, then the code should change as the following:
        `self.to_be_added[name] = np.nan_to_num((ev[:, 0] - ev[:, 1]) / ev[:, 2])` instead of `self.to_be_added[name] = np.nan_to_num((ev[:, 0] - ev[:, 2]) / ev[:, 0])`.

++++++++++++++++++++++++++
Environment: 
OS: Ubuntu 18.04
Python version: 3.7.4
Pyntcloud installation: conda
Version: master branch

**Comment by daavoo** [comment]
Hola @denabazazian ! Thanks for the detailed report.

1.
You are computing the eigenvalues correctly. However the return of `add_scalar_field` are actually string identifiers, not the actual values of the scalar field (as stated in: https://github.com/daavoo/pyntcloud/blob/master/pyntcloud/core_class.py#L214).

You can check that what `add_scalar_field` actually does is adding 3 new columns to your PyntCloud's `points` DataFrame:

```python
print(pcd1.points.head)  # See the current columns
ev = pcd1.add_scalar_field("eigen_values", k_neighbors=k_neighbors)
print(pcd1.points.head)  # You should now see 3 new columns
```

In order to access to the eigenvalues you can select those columns from your PyntCloud:

```python
actual_eigenvalues = pcd1.loc[:, ev]
# To get numpy arrays: actual_eigenvalues = pcd1.loc[:, ev].values
```

2. Good catch. The error is in the equation. The code is correct. Fixing it could be a nice first Pull Request :)

Please feel free to re-open if you consider this unsolved

**Comment by denabazazian** [comment]
Muchas gracias @daavoo ! Your suggestion was very useful and it solved my problem. 
I have updated my repository for Edge Extraction [https://github.com/denabazazian/Edge_Extraction] based on pyntcloud. 
Also, I fixed the Anisotropy equation by a Pull Request.
