### ISSUE TITLE
plot() isn't interactive in jupyter notebook

### ISSUE THREAD

**Issue by ziliHarvey** [daavoo/pyntcloud#275]
![Screenshot from 2020-03-06 15-07-49](https://user-images.githubusercontent.com/43801975/76118950-5d2de280-5fbc-11ea-85c5-e5b4b9262510.png)

Using plot in .py file generates a gui with points in 3d that can be dragged, manipulated by mouse. However, in Jupyter Notebook, only static image is shown. Can anyone help me with this?

**Comment by daavoo** [comment]
Hola @ziliHarvey . It looks like you are plotting with the matplotlib backend. 

In order to make the plot interactive you can either:

A) Invoke the %matplotlib notebook magic command before calling the plot (More info at https://medium.com/@1522933668924/using-matplotlib-in-jupyter-notebooks-comparing-methods-and-some-tips-python-c38e85b40ba1)

B) Use the pythreejs backend, by passing the argument to `plot`:

```python
pc.plot(backend="pythreejs", initial_point_size=0.02)
```

Feel free to re-open if the issue persists after aplying the proposed solutions
